### ISSUE TITLE
DeleteではなくAchiveにしたい

### ISSUE THREAD

**Issue by KatsuYuzu** [JAZUG-Sapporo/kita-az-twitter-bot#25]
過去メッセージ見て文面考えるので消えると辛い。

**Comment by jsakamoto** [comment]
#28 はとりあえずはマージ & デプロイ完了しました。

なお、ここまで実装すると欲が出てきて、いったんアーカイブにまわしたのを、また復活させる機能付けたくなりました :smile: 

でもそこまで考えて、待てよ、これって、"Archive" っていう機能名・表記よりも「ゴミ箱」機能といったほうが「アーカイブ」というよりわかりやすかしら? とか思ったり思わなかったり。

**Comment by KatsuYuzu** [comment]
ありがとうございます。
方向性いいのかわからなかったのでとりあえずミニマムで送りました。コピペして新規で作れば復元もできますし。アーカイブがあるなら当然復元もって連想しましたが、用途的に復元することほぼないとも思いまして。
古い物を避けとくって意味ではアーカイブかなあ。

**Comment by jsakamoto** [comment]
> 用途的に復元することほぼないとも思いまして。

そこは同感。
ただし、操作ミスに対する救済として、です。

このプルリクもらうまでは削除しかなくて、削除したら復活できなかったわけですがw、こうしてアーカイブ機能ができてみたら、アーカイブ一覧から復活させるチャンスができたので、そこで欲が出た次第。

**Comment by KatsuYuzu** [comment]
まあ、議論するより実装した方が早いレベルですね笑
アーカイブ画面にある分には通常操作してるユーザーの邪魔にもならないので、機能過多ではないですね。暇見て。

**Comment by jsakamoto** [comment]
あー、 @KatsuYuzu が手を下す必要はないですよ。思いついたのは自分ですし。面白そうとおもうところいじってもらうだけでありがたいです。

ので、復活機能実装については放置で構わないですし、あるいは実装したくなったらやっていただいてプルリク送ってもらうのも大歓迎です。

(でも自分もまだ復活機能実装は先送りで、それより先に、拡張スクリプトに関するドキュメントを優先してやります)

**Comment by KatsuYuzu** [comment]
アーカイブ日つけて、アーカイブ一覧でぱらぐらふ別けたくなった

**Comment by KatsuYuzu** [comment]
諸々 done！
